基本上可以用了

diff --git a/shauto b/shauto
--- a/shauto
+++ b/shauto
@@ -1,7 +1,6 @@
 #!/bin/bash
 #
-#auto_shell.sh
-#批量维护工具
+#shell运维自动化工具
 
 
 #引用未定义的变量时报错并退出脚本
@@ -9,31 +8,60 @@ set -o nounset
 #命令执行失败时报错并退出脚本
 #set -o errexit
 
-#当前绝对路径
-PWD_REAL="$(cd $(dirname $0);pwd)"
-#要执行命令的主机列表
-HOSTLIST=""
-#用户及端口
-USER="root"
-PORT=22
-#要执行的命令
-CMD=""
-#定制ssh连接选项
+#脚本所在目录的绝对路径
+SCRIPT_DIR="$(cd $(dirname $0);pwd)"
+#脚本绝对路径
+SCRIPT_PATH="${SCRIPT_DIR}/$(basename $0)"
+#hosts文件默认路径
+HOSTS_FILE="hosts"
+#临时保存数据目录
+TEMP_DIR="/tmp/$(basename $0)_temp_dir"
+
+#要执行的模块
+MODULE=""
+#模块参数
+MODULE_ARGS=""
+#执行自定义脚本文件
+BATCH_FILE=""
+
+#远程ssh用户
+REMOTE_USER="chenwei" 
+#远程ssh端口
+REMOTE_PORT=22
+#远程shell
+REMOTE_SHELL="bash"
+#私钥
+PRIVATE_KEY_FILE=""
+#ssh连接超时时间
+TIMEOUT=10
+#ssh连接选项
+#SSH_ARGS="-o StrictHostKeyChecking=no -o ConnectTimeout=${TIMEOUT}"
 SSH_ARGS="-o StrictHostKeyChecking=no"
 #并发数量
-PARALL=1
-#远程SHELL
-REMOTE_SHELL="bash"
-#临时目录
-TEMP_DIR="/tmp/$(basename $0)_temp_dir"
+FORKS=5
+
+#要执行命令的主机列表
+HOSTLIST=()
+#主机匹配模式
+PATTERN=""
+#要执行的命令
+CMDLIST="set -o errexit"
 #冗余模式
 VERBOSE=""
-#当前时间
-#DATE="$(date +%Y%m%d%H%M%S)"
 
 
 usage() {
-    :
+    cat <<EOF
+Usage: $(basename $0) <host-pattern> [option]...
+
+Options:
+  -a
+  -m
+  -u
+  -p
+EOF
+    
+    exit 1
 }
 
 
@@ -53,49 +81,118 @@ error() {
 }
 
 
-#检查命令返回值，判断命令是否成功执行
-return_code_check() {
-    if [[ "$?" -eq 0 ]]; then
-        echo "$@ success!"
-    else
-        error "$@ failed!"
-    fi
-}
-
-
-#创建临时目录
-create_temp() {
+#创建临时目录，保存执行结果
+create_temp_dir() {
     [[ -d "$TEMP_DIR" ]] && rm -rf "$TEMP_DIR" &>/dev/null
     mkdir -m 700 $TEMP_DIR
 }
 
 
+hostfile_check() {
+    :
+}
+
+
+#解析hosts文件
+hostfile_parse() {
+    [[ -f "$HOSTS_FILE" ]] || error "$HOSTS_FILE does not exist!"
+
+    #hostfile语法检测
+    #hostfile_check
+
+    if grep "^\[$PATTERN\]" "$HOSTS_FILE" &>/dev/null; then
+        #匹配组
+        local match_hosts="$(sed -n "/^\[$PATTERN\]/,/^\[/p" "$HOSTS_FILE" | sed '/^\[/d' | sort | uniq)"
+        local host=""
+        for host in $match_hosts; do
+            #向数组添加元素
+            HOSTLIST+=("$host")
+        done
+    elif [[ "$PATTERN" =~ ^[1-9][0-9]*\.[0-9]+\.[0-9]+\.[0-9]+$ ]] \
+        && grep "^$PATTERN" "$HOSTS_FILE" &>/dev/null; then
+        #匹配单个IP
+        HOSTLIST+=("$PATTERN")
+    elif [[ "$PATTERN" == "all" || "$PATTERN" == "*" ]]; then
+        #匹配所有主机
+        local match_hosts="$(grep '^[1-9]' "$HOSTS_FILE" | sort | uniq)"
+        local host=""
+        for host in $match_hosts; do
+            HOSTLIST+=("$host")
+        done
+    else
+        error "$PATTERN does not match any host in $HOSTS_FILE"
+    fi
+}
+
+
+#管理文件/目录属性
+#Usage: attrib [option]... path
+#Options:
+#  -u owner: 属主，可选，默认值"$REMOTE_USER"
+#  -g group: 属组，可选，默认值"$REMOTE_USER"
+#  -m mode: 权限，可选，默认值"0644"
+#  -r/-R: 是否递归处理目录，可选，默认不递归处理目录
+attrib() {
+    local owner="$REMOTE_USER"
+    local group="$owner"
+    local mode="0644"
+    local recursive=""
+
+    while getopts :u:g:m:rR option; do
+        case "$option" in
+            u) owner="$OPTARG";;
+            g) group="$OPTARG";;
+            m) mode="$OPTARG";;
+            r|R) recursive="-R";;
+            \?) error "attrib: invalid option -${OPTARG}";;
+            \:) error "attrib: must provide a value for -${OPTARG} option";;
+        esac
+    done
+    #处理完选项，$1变为非选项参数
+    shift $(($OPTIND - 1)) 
+    unset OPTIND
+
+    [[ -n "$1" ]] || error "attrib: must specify a path"
+    CMDLIST="$CMDLIST
+chmod $recursive $mode $@ && chown $recursive ${owner}:${group} $@"
+}
+
+
+#传输文件/目录到远程主机
 scp_file() {
     :
 }
 
+
+#连接远程主机并执行命令
 ssh_cmd() {
     local host="$1"
-    local temp_file="${TEMP_DIR}/${host}"
+    local temp_file_success="${TEMP_DIR}/${host}.success"
+    local temp_file_failed="${TEMP_DIR}/${host}.failed"
 
-    echo "$CMD" | ssh -l "$USER" -p "$PORT" "$SSH_ARGS" "$host" "$REMOTE_SHELL" &>"$temp_file"
-    if [[ "$?" -eq 0 ]]; then
+    echo "$CMDLIST" | 
+    ssh -l "$REMOTE_USER" -p "$REMOTE_PORT" "$SSH_ARGS" "$host" "$REMOTE_SHELL" \
+        >>"$temp_file_success" 2>>"$temp_file_failed"
+
+    rc="$?"
+    if [[ "$rc" -eq 0 ]]; then
         if [[ -n "$VERBOSE" ]]; then
-            sed "s/^/$host: /" "$temp_file"
+            #success "$host | success | rc=0 >>"
+            tail -100 "$temp_file_success" | \
+            awk -v host="$host" '{print "\033[32m1"host"\033[0m: "$0}'
         else
-            success "$host: success"
+            success "$host | success | rc=0"
         fi
     else
-        if [[ -n "$VERBOSE" ]]; then
-            cat "$temp_file"
-        else
-            failed "$host: failed"
-        fi
+        failed "$host | failed | rc=${rc} >>\n$(cat $temp_file_failed)"
     fi   
 }
 
 
+#并发控制
 parall_run() {
+    local module="${1:-ssh_cmd}"
+
     #建立命名管道文件，为了不受干扰，将文件打开，将文件inode信息删除
     local pipe="$(mktemp -u)" 
     mkfifo "$pipe" 
@@ -104,16 +201,16 @@ parall_run() {
     rm -f "$pipe" 
 
     #往命名管道存入值，存入多少个值就表示并发量多大
-    for ((i=1;i<=${PARALL};i++)); do 
+    for ((i=1;i<=${FORKS};i++)); do 
         echo >&5
     done 
   
-    for host in $HOSTLIST; do
+    for host in ${HOSTLIST[@]}; do
         #从命名管道读取一个值
         #如果此时命名管道中没有值，read会阻塞直到读取到一个值  
         read -u 5
-        #执行具体的动作action，执行完后放入一个值到命名管道
-        (ssh_cmd "$host"; echo >&5) &
+        #执行具体的动作，执行完后放入一个值到命名管道
+        ($module "$host"; echo >&5) &
     done
 
     #等待所有后台进程执行完毕
@@ -123,148 +220,127 @@ parall_run() {
 }
 
 
-
-#获取命令的绝对路径
-#Arguments:
-#  $1: 传入命令名
-#Returns:
-#  传入命令的绝对路径
-get_cmd_abspath() {
-    local cmd="$1"
-
-    if which "$cmd" &>/dev/null; then
-        echo "$(which $cmd)"
-        return 0
-    else
-        error "no $cmd in ($PATH)"
+cmdline_arguments_parse() {
+    if [[ "$#" -lt 3 ]]; then
+        usage
     fi
-}
 
+    #第一个参数必须为匹配模式字符串
+    if [[ -n "$1" && "${1#-}" == "$1" ]]; then
+        PATTERN="$1"
+        shift
+    else
+        usage
+    fi
 
-#管理远程主机文件/目录的属性
-#Arguments:
-#  $1：远程文件/目录路径jj
-#  $2：属主(owner)
-#  $3：属组(group)
-#  $4: 文件权限
-file() {
-    local path="$1"
-    local owner="$2"
-    local group="$3"
-    local mode="$4"
-}
-
-
-#复制本地文件/目录到远程主机
-#Arguments:
-#  $1: 文件在本地主机的路径
-#  $2: 文件在远程主机的存放路径
-#  $3: 
-copy() {
-    local src="$1"
-    local dest="$2"
-    scp $src $user@$host:$dest
-    # 如果目的路径在其他用户下怎么办
-    # 先copy到$user下一个临时目录
-    # 然后再sudo cp到对应目录
-}
-
-
-parse_arguments() {
-    while [[ -n "${1:-}" ]]; do
-        case "$1" in
-        -h)
-            while [[ -n "$2" && "${2#-}" == "$2" ]]; do
-                HOSTLIST="$2
-$HOSTLIST"
-                shift
-            done
-            shift
+    while getopts :m:a:b:h:u:p:s:i:f:o:v option; do
+        case "$option" in
+        m)
+            MODULE="$OPTARG"
             ;;
-        -H)
-            while [[ -n "$2" && "${2#-}" == "$2" ]]; do
-                local hostfile="$2"
-                [[ -f "$hostfile" ]] && error "Host file '$hostfile' does not exist!"
-                HOSTLIST="$(cat $hostfile | sed 's/#.*//' | egrep -v "^ *$")
-$HOSTLIST"
-                shift
-            done
-            shift
+        a)
+            MODULE_ARGS="$OPTARG"
+            #MODULE_ARGS+=($OPTARG)
             ;;
-        -u)
-            USER="$2"
-            shift 2
+        b)
+            BATCH_FILE="$OPTARG"
             ;;
-        -p)
-            PORT="$2"
-            shift 2
+        h)
+            HOSTS_FILE="$OPTARG"
             ;;
-        -c)
-            CMD="$CMD
-$2"
-            shift 2
+        u)
+            REMOTE_USER="$OPTARG"
             ;;
-        -C)
-            #可以同时执行多个文件
-            while [[ -n "$2" && "${2#-}" == "$2" ]]; do
-                local scriptfile="$2"
-                [[ -f "$scriptfile" ]] || error "Script File $scriptfile does not exist!"
-                CMD="$CMD
-$(cat $scriptfile)"
-                shift
-            done
-            shift
+        p)
+            REMOTE_PORT="$OPTARG"
             ;;
-        -o)
-            SSH_ARGS="$SSH_ARGS -o $2"
-            shift 2
+        s)
+            REMOTE_SHELL="$OPTARG"
             ;;
-        -s)
-            REMOTE_SHELL="$2"
-            shift 2
+        i)
+            PRIVATE_KEY_FILE="$OPTARG"
             ;;
-        -f)
-            PARALL="$2"
-            shift 2
+        f)
+            FORKS="$OPTARG"
             ;;
-        -t)
-            if [[ -n "$2" && "${2#-}" == "$2" ]]; then
-                local ssh_timeout="$2"
-            fi
-            SSH_ARGS="$SSH_ARGS -o ConnectTimeout=$ssh_timeout"
-            shift 2
+        o)
+            SSH_ARGS="$SSH_ARGS -o $OPTARG"
             ;;
-        -v)
-            VERBOSE="verbose"
-            shift
+        v)
+            VERBOSE="yes"
             ;;
-        --help)
-            usage
-            exit
+        \?)
+            error "invalid option: -${OPTARG}"
             ;;
-        *)
-            echo "invalid command - \"$1\"" 1>&2
-            usage
-            exit 1
+        \:)
+            error "must provide a value for -${OPTARG} option"
             ;;
         esac
     done
+
+    #OPTIND是全局变量，会影响到其他模块的getopts
+    #每次通过getopts处理完选项后都要unset掉
+    unset OPTIND
+}
+
+
+cmd() {
+    CMDLIST="$CMDLIST
+$@"
+}
+
+
+alive() {
+    local host="$1"
+    local ping_cmd=""
+    #local temp_file_success="${TEMP_DIR}/${host}.success"
+    local temp_file_failed="${TEMP_DIR}/${host}.failed"
+
+    if which fping &>/dev/null; then
+        ping_cmd="$(which fping)"
+    else
+        ping_cmd="$(which ping) -c 4 -q"
+    fi
+
+    $ping_cmd $host >/dev/null 2>"$temp_file_failed"
+    local rc="$?"
+    if [[ "$rc" -eq 0 ]]; then
+        success "$host | success | rc=0"
+    else
+        failed "$host | failed | rc=${rc} >>\n$(cat $temp_file_failed)"
+    fi
 }
 
 
 main() {
     #解析命令行参数
-    parse_arguments "$@"
-
-    #至少要指定一个host
-    [[ -z "$HOSTLIST" ]] && error "No host found, please use -h/-H specify at least one host"
-    #至少要存在一个命令
-    #[[ -z "$CMD" ]] && error "No command found, please use -c/-C specify at least one command"
-
+    cmdline_arguments_parse "$@"
+    #解析hosts文件
+    hostfile_parse
     #创建临时目录
-    create_temp
+    create_temp_dir
 
-    #开始执行, parall_run "ssh_cmd", eval "ssh_cmd"
+    if [[ -n "$MODULE" ]]; then
+        #alive和scp_file都是本地执行的，属于特例
+        if [[ "$MODULE" == "alive" || "$MODULE" == "scp_file" ]]; then
+            parall_run "$MODULE"
+            exit
+        else
+            $MODULE $MODULE_ARGS
+        fi
+    elif [[ -z "$MODULE" && -n "$MODULE_ARGS" ]]; then
+        #如果不提供-m但是提供-a参数，则默认使用cmd模块
+        cmd "$MODULE_ARGS"
+    elif [[ -n "$BATCH_FILE" ]]; then
+        . "$BATCH_FILE"
+    else
+        failed "nothing to do"
+        usage
+    fi
+
+    #远程主机执行的命令列表不能为空
+    [[ "${#CMDLIST}" -le 15 ]] && error "no command found"
+    #并发执行命令
     parall_run
 }
 
